set shell := ["powershell.exe", "-Command"]

run:
    idf.py fullclean
    idf.py set-target esp32s3
    idf.py build
    idf.py -p COM3 flash monitor

build:
    idf.py set-target esp32s3
    idf.py build
    
clean:
    idf.py fullclean
